[project]
name = 'pynixf'
version = '0.1.0'
description = 'Python bindings for libnixf'
requires-python = ">=3.12"
dependencies = []



[build-system]
build-backend = 'mesonpy'
requires = ["meson-python"]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
